{{- if .Values.bucketClass.create }}
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: {{ include "versitygw-cosi-driver.bucketClassName" . }}
  labels:
    {{- include "versitygw-cosi-driver.labels" . | nindent 4 }}
driverName: {{ include "versitygw-cosi-driver.driverName" . }}
deletionPolicy: {{ .Values.bucketClass.deletionPolicy }}
{{- with .Values.bucketClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
